### ISSUE TITLE
Windows cannot detect language

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#170]
Select English when it's not possible to detect LOCALE in Welcome Screen.

**Comment by willvincent** [comment]
This issue doesn't seem to only affect windows. I think the reason is because locale are more specific than just the two character code.

English, for example can be `en-US`, `en-UK`, etc.  PR #181 should resolve.

Changes the default selection so that _if_ a value is returned from getLocale, that value is split on `-`, and only the first part used.  So on my mac when getLocale() gives `en-US` it'll still set the default value to `en`.

```
$('#locales-list').val(app.getLocale() ? app.getLocale().split('-')[0] : 'en');
```

**Comment by willvincent** [comment]
Updated PR with better logic after I noticed some of the translations files use the full locale, and others are just a two character code. New logic will support both, and default to english if nothing matches.

```
// Try to figure out user's language
if (app.getLocale() in i18n.fullLocaleList) {
  $('#locales-list').val(app.getLocale());
} else if (app.getLocale().split('-')[0] in i18n.fullLocaleList) {
  $('#locales-list').val(app.getLocale().split('-')[0]);
} else {
  $('#locales-list').val('en');
}
```

**Comment by rafajaques** [comment]
> Changes the default selection so that if a value is returned from getLocale, that value is split on -, and only the first part used. So on my mac when getLocale() gives en-US it'll still set the default value to en.

Nice! I didn't noticed that issue here because my mac is `pt-BR`, the same available language.
